# coding: utf-8

"""
    GroupDocs.Translation SDK

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 23.12.0
    Contact: anton.perhunov@aspose.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

import groupdocs_translation_cloud
from groupdocs_translation_cloud.api.file_api import FileApi  # noqa: E501
from groupdocs_translation_cloud.rest import ApiException


class TestFileApi(unittest.TestCase):
    """FileApi unit test stubs"""

    def setUp(self):
        self.api = groupdocs_translation_cloud.api.file_api.FileApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_file_upload_post(self):
        """Test case for file_upload_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
