# coding: utf-8

"""
    GroupDocs.Translation SDK

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 23.9.4
    Contact: anton.perhunov@aspose.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import groupdocs-translation-cloud
from groupdocs-translation-cloud.models.html_file_request import HtmlFileRequest  # noqa: E501
from groupdocs-translation-cloud.rest import ApiException

class TestHtmlFileRequest(unittest.TestCase):
    """HtmlFileRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test HtmlFileRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HtmlFileRequest`
        """
        model = groupdocs-translation-cloud.models.html_file_request.HtmlFileRequest()  # noqa: E501
        if include_optional :
            return HtmlFileRequest(
                source_language = 'en', 
                target_languages = [
                    ''
                    ], 
                file = 'YQ==', 
                original_file_name = '', 
                url = '', 
                origin = '', 
                saving_mode = 'Files', 
                output_format = '0'
            )
        else :
            return HtmlFileRequest(
        )
        """

    def testHtmlFileRequest(self):
        """Test HtmlFileRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
