# coding: utf-8

"""
    GroupDocs.Translation.ApiGateway.Web

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import GroupDocs.Translation.Api
from GroupDocs.Translation.Api.models.http_status_code import HttpStatusCode  # noqa: E501
from GroupDocs.Translation.Api.rest import ApiException

class TestHttpStatusCode(unittest.TestCase):
    """HttpStatusCode unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testHttpStatusCode(self):
        """Test HttpStatusCode"""
        # inst = HttpStatusCode()

if __name__ == '__main__':
    unittest.main()
