# coding: utf-8

"""
    GroupDocs.Translation SDK

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 23.10.5
    Contact: anton.perhunov@aspose.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

import groupdocs_translation_cloud
from groupdocs_translation_cloud.api.translation_api import TranslationApi  # noqa: E501
from groupdocs_translation_cloud.rest import ApiException


class TestTranslationApi(unittest.TestCase):
    """TranslationApi unit test stubs"""

    def setUp(self):
        self.api = groupdocs_translation_cloud.api.translation_api.TranslationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_auto_post(self):
        """Test case for auto_post

        Translate any supported file  # noqa: E501
        """
        pass

    def test_csv_post(self):
        """Test case for csv_post

        Translate CSV and TSV files  # noqa: E501
        """
        pass

    def test_document_post(self):
        """Test case for document_post

        Translate Microsoft Word documents, rtf, txt, odt  # noqa: E501
        """
        pass

    def test_document_request_id_get(self):
        """Test case for document_request_id_get

        Return document translation status.  Also return URLs for downloading of translated document if translation was successful  # noqa: E501
        """
        pass

    def test_document_trial_get(self):
        """Test case for document_trial_get

        Return document translation status for trial request.  Also return URLs for downloading of translated document if translation was successful  # noqa: E501
        """
        pass

    def test_document_trial_post(self):
        """Test case for document_trial_post

        Trial translate Microsoft Word documents, rtf, txt, odt without conversation. Translate only first page or 1000 symbols.  # noqa: E501
        """
        pass

    def test_hc_get(self):
        """Test case for hc_get

        Health check for all services.  # noqa: E501
        """
        pass

    def test_html_post(self):
        """Test case for html_post

        Translate HTML files  # noqa: E501
        """
        pass

    def test_hugo_get(self):
        """Test case for hugo_get

        Get hugo syntax structure from markdown file  # noqa: E501
        """
        pass

    def test_hugo_post(self):
        """Test case for hugo_post

        Run hugo syntax structure analyzing from markdown file  # noqa: E501
        """
        pass

    def test_image_to_file_post(self):
        """Test case for image_to_file_post

        Translate image or scanned pdf and return file  # noqa: E501
        """
        pass

    def test_image_to_text_post(self):
        """Test case for image_to_text_post

        Translate text on image or scanned pdf  # noqa: E501
        """
        pass

    def test_languages_get(self):
        """Test case for languages_get

        Return list of available language pairs  # noqa: E501
        """
        pass

    def test_markdown_post(self):
        """Test case for markdown_post

        Translate Markdown files  # noqa: E501
        """
        pass

    def test_pdf_post(self):
        """Test case for pdf_post

        Translate pdf files  # noqa: E501
        """
        pass

    def test_pdf_trial_post(self):
        """Test case for pdf_trial_post

        Trial pdf translation. Translate only first page without conversion to another format.  # noqa: E501
        """
        pass

    def test_presentation_post(self):
        """Test case for presentation_post

        Translate Microsoft PowerPoint presentations, odp  # noqa: E501
        """
        pass

    def test_resx_post(self):
        """Test case for resx_post

        Translate Resx files  # noqa: E501
        """
        pass

    def test_spreadsheet_post(self):
        """Test case for spreadsheet_post

        Translate Microsoft Excel workbooks, ods  # noqa: E501
        """
        pass

    def test_srt_post(self):
        """Test case for srt_post

        Translate Srt files  # noqa: E501
        """
        pass

    def test_text_post(self):
        """Test case for text_post
        Translate text  # noqa: E501
        """
        self.api = groupdocs_translation_cloud.api.TranslationApi()
        self.api.api_client.configuration.client_id = "translate.cloud"
        self.api.api_client.configuration.client_secret = "5d0da472782620373473703904631795"

        text_request = groupdocs_translation_cloud.TextRequest(source_language="en"
                                                               , target_languages=["es", "fr", "ru"]
                                                               , texts=["Hello World!", "This is a test text"]
                                                               , origin="your_application_name"
                                                               , contains_markdown=False)
        response = self.api.text_post(text_request)
        if response.status == 202:
            while True:
                status_response = self.api.text_request_id_get(response.id)
                if status_response.status == groupdocs_translation_cloud.HttpStatusCode.OK:
                    for lang in status_response.translations:
                        print(lang.key)
                    break

        pass

    def test_text_request_id_get(self):
        """Test case for text_request_id_get

        Return text translation status.  Also return translated text if translation was successful  # noqa: E501
        """
        pass

    def test_text_trial_get(self):
        """Test case for text_trial_get

        Return text translation status for trial requests.  Also return translated text if translation was successful  # noqa: E501
        """
        pass

    def test_text_trial_post(self):
        """Test case for text_trial_post

        Trial translate text. Translate only 1000 symbols.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
