# coding: utf-8

"""
    GroupDocs.Translation SDK

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 23.10.5
    Contact: anton.perhunov@aspose.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import groupdocs_translation_cloud
from groupdocs_translation_cloud.models.cloud_file_request import CloudFileRequest  # noqa: E501
from groupdocs_translation_cloud.rest import ApiException

class TestCloudFileRequest(unittest.TestCase):
    """CloudFileRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test CloudFileRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CloudFileRequest`
        """
        model = groupdocs_translation_cloud.models.cloud_file_request.CloudFileRequest()  # noqa: E501
        if include_optional :
            return CloudFileRequest(
                format = '', 
                out_format = '', 
                request_id = '', 
                ids = [
                    56
                    ], 
                url = '', 
                size = 56, 
                masters = True, 
                formatting = True, 
                origin = '', 
                elements = [
                    56
                    ], 
                ranges = {
                    'key' : groupdocs_translation_cloud.models.worksheet_data.WorksheetData(
                        rows = [
                            56
                            ], 
                        columns = [
                            56
                            ], 
                        ranges = [
                            groupdocs_translation_cloud.models.string_string_tuple.StringStringTuple(
                                item1 = '', 
                                item2 = '', )
                            ], )
                    }, 
                short_code_dict = {
                    'key' : [
                        ''
                        ]
                    }, 
                front_matter_list = [
                    [
                        ''
                        ]
                    ], 
                original_name = '', 
                separator = '', 
                saving_mode = 'Files', 
                details = {
                    'key' : ''
                    }
            )
        else :
            return CloudFileRequest(
        )
        """

    def testCloudFileRequest(self):
        """Test CloudFileRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
