# coding: utf-8

"""
    GroupDocs.Translation.ApiGateway.Web

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import GroupDocs.Translation.Api
from GroupDocs.Translation.Api.models.auto_post_request import AutoPostRequest  # noqa: E501
from GroupDocs.Translation.Api.rest import ApiException

class TestAutoPostRequest(unittest.TestCase):
    """AutoPostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test AutoPostRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AutoPostRequest`
        """
        model = GroupDocs.Translation.Api.models.auto_post_request.AutoPostRequest()  # noqa: E501
        if include_optional :
            return AutoPostRequest(
                format = 'Unknown', 
                output_format = '', 
                masters = True, 
                formatting = True, 
                route = '', 
                separator = '', 
                elements = [
                    56
                    ], 
                ranges = {
                    'key' : GroupDocs.Translation.Api.models.worksheet_data.WorksheetData(
                        rows = [
                            56
                            ], 
                        columns = [
                            56
                            ], 
                        ranges = [
                            GroupDocs.Translation.Api.models.string_string_tuple.StringStringTuple(
                                item1 = '', 
                                item2 = '', )
                            ], )
                    }, 
                short_code_list = {
                    'key' : [
                        [
                            ''
                            ]
                        ]
                    }, 
                front_matter_list = [
                    [
                        ''
                        ]
                    ], 
                source_language = 'en', 
                target_languages = [
                    ''
                    ], 
                file = 'YQ==', 
                original_file_name = '', 
                url = '', 
                origin = '', 
                saving_mode = 'Files'
            )
        else :
            return AutoPostRequest(
                format = 'Unknown',
                output_format = '',
                source_language = 'en',
                target_languages = [
                    ''
                    ],
        )
        """

    def testAutoPostRequest(self):
        """Test AutoPostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
