# coding: utf-8

"""
    GroupDocs.Translation SDK

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 23.9.4
    Contact: anton.perhunov@aspose.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import groupdocs-translation-cloud
from groupdocs-translation-cloud.models.image_to_text_request import ImageToTextRequest  # noqa: E501
from groupdocs-translation-cloud.rest import ApiException

class TestImageToTextRequest(unittest.TestCase):
    """ImageToTextRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ImageToTextRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ImageToTextRequest`
        """
        model = groupdocs-translation-cloud.models.image_to_text_request.ImageToTextRequest()  # noqa: E501
        if include_optional :
            return ImageToTextRequest(
                format = 'Unknown', 
                source = 'en', 
                targets = [
                    ''
                    ], 
                file = 'YQ==', 
                url = '', 
                rotate = 56, 
                ishandwritten = True, 
                origin = '', 
                route = ''
            )
        else :
            return ImageToTextRequest(
        )
        """

    def testImageToTextRequest(self):
        """Test ImageToTextRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
