# coding: utf-8

"""
    GroupDocs.Translation.ApiGateway.Web

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

import GroupDocs.Translation.Api
from GroupDocs.Translation.Api.api.transport_api import TransportApi  # noqa: E501
from GroupDocs.Translation.Api.rest import ApiException


class TestTransportApi(unittest.TestCase):
    """TransportApi unit test stubs"""

    def setUp(self):
        self.api = GroupDocs.Translation.Api.api.transport_api.TransportApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_auto_post(self):
        """Test case for auto_post

        Translate any supported file  # noqa: E501
        """
        pass

    def test_csv_post(self):
        """Test case for csv_post

        Translate CSV and TSV files  # noqa: E501
        """
        pass

    def test_document_post(self):
        """Test case for document_post

        Translate Microsoft Word documents, rtf, txt, odt  # noqa: E501
        """
        pass

    def test_document_request_id_get(self):
        """Test case for document_request_id_get

        Return document translation status.  Also return URLs for downloading of translated document if translation was successful  # noqa: E501
        """
        pass

    def test_hc_get(self):
        """Test case for hc_get

        Health check for all services.  # noqa: E501
        """
        pass

    def test_html_post(self):
        """Test case for html_post

        Translate HTML files  # noqa: E501
        """
        pass

    def test_hugo_get(self):
        """Test case for hugo_get

        Get hugo syntax structure from markdown file  # noqa: E501
        """
        pass

    def test_hugo_post(self):
        """Test case for hugo_post

        Run hugo syntax structure analyzing from markdown file  # noqa: E501
        """
        pass

    def test_image_to_file_post(self):
        """Test case for image_to_file_post

        Translate image or scanned pdf and return file  # noqa: E501
        """
        pass

    def test_image_to_text_post(self):
        """Test case for image_to_text_post

        Translate text on image or scanned pdf  # noqa: E501
        """
        pass

    def test_languages_get(self):
        """Test case for languages_get

        Return list of available language pairs  # noqa: E501
        """
        pass

    def test_markdown_post(self):
        """Test case for markdown_post

        Translate Markdown files  # noqa: E501
        """
        pass

    def test_pdf_post(self):
        """Test case for pdf_post

        Translate pdf files  # noqa: E501
        """
        pass

    def test_presentation_post(self):
        """Test case for presentation_post

        Translate Microsoft PowerPoint presentations, odp  # noqa: E501
        """
        pass

    def test_resx_post(self):
        """Test case for resx_post

        Translate RESX files  # noqa: E501
        """
        pass

    def test_spreadsheets_post(self):
        """Test case for spreadsheets_post

        Translate Microsoft Excel workbooks, ods  # noqa: E501
        """
        pass

    def test_text_post(self):
        """Test case for text_post

        Translate text  # noqa: E501
        """
        pass

    def test_text_request_id_get(self):
        """Test case for text_request_id_get

        Return text translation status.  Also return translated text if translation was successful  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
