# coding: utf-8

"""
    GroupDocs.Translation SDK

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 23.10.5
    Contact: anton.perhunov@aspose.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

import groupdocs_translation_cloud
from groupdocs_translation_cloud.api.swagger_api import SwaggerApi  # noqa: E501
from groupdocs_translation_cloud.rest import ApiException


class TestSwaggerApi(unittest.TestCase):
    """SwaggerApi unit test stubs"""

    def setUp(self):
        self.api = groupdocs_translation_cloud.api.swagger_api.SwaggerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_swagger_spec_get(self):
        """Test case for swagger_spec_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
