# coding: utf-8

"""
    GroupDocs.Translation SDK

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 24.3.0
    Contact: anton.perhunov@aspose.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import groupdocs_translation_cloud
from groupdocs_translation_cloud.models.health_check_entity import HealthCheckEntity  # noqa: E501
from groupdocs_translation_cloud.rest import ApiException

class TestHealthCheckEntity(unittest.TestCase):
    """HealthCheckEntity unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test HealthCheckEntity
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HealthCheckEntity`
        """
        model = groupdocs_translation_cloud.models.health_check_entity.HealthCheckEntity()  # noqa: E501
        if include_optional :
            return HealthCheckEntity(
                name = '', 
                is_healthy = True, 
                message = ''
            )
        else :
            return HealthCheckEntity(
        )
        """

    def testHealthCheckEntity(self):
        """Test HealthCheckEntity"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
