# coding: utf-8

"""
    GroupDocs.Translation SDK

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 24.3.0
    Contact: anton.perhunov@aspose.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictBool, StrictStr

class HealthCheckEntity(BaseModel):
    """
    HealthCheckEntity
    """
    name: Optional[StrictStr] = None
    is_healthy: Optional[StrictBool] = Field(None, alias="isHealthy")
    message: Optional[StrictStr] = None
    __properties = ["name", "isHealthy", "message"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> HealthCheckEntity:
        """Create an instance of HealthCheckEntity from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # set to None if name (nullable) is None
        # and __fields_set__ contains the field
        if self.name is None and "name" in self.__fields_set__:
            _dict['name'] = None

        # set to None if message (nullable) is None
        # and __fields_set__ contains the field
        if self.message is None and "message" in self.__fields_set__:
            _dict['message'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> HealthCheckEntity:
        """Create an instance of HealthCheckEntity from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return HealthCheckEntity.parse_obj(obj)

        _obj = HealthCheckEntity.parse_obj({
            "name": obj.get("name"),
            "is_healthy": obj.get("isHealthy"),
            "message": obj.get("message")
        })
        return _obj

