# coding: utf-8

"""
    GroupDocs.Translation SDK

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 24.3.0
    Contact: anton.perhunov@aspose.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictStr

class HealthCheckStatus(BaseModel):
    """
    HealthCheckStatus
    """
    kafka_delivery_status: Optional[StrictStr] = Field(None, alias="kafkaDeliveryStatus")
    cloud_status: Optional[StrictStr] = Field(None, alias="cloudStatus")
    __properties = ["kafkaDeliveryStatus", "cloudStatus"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> HealthCheckStatus:
        """Create an instance of HealthCheckStatus from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # set to None if kafka_delivery_status (nullable) is None
        # and __fields_set__ contains the field
        if self.kafka_delivery_status is None and "kafka_delivery_status" in self.__fields_set__:
            _dict['kafkaDeliveryStatus'] = None

        # set to None if cloud_status (nullable) is None
        # and __fields_set__ contains the field
        if self.cloud_status is None and "cloud_status" in self.__fields_set__:
            _dict['cloudStatus'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> HealthCheckStatus:
        """Create an instance of HealthCheckStatus from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return HealthCheckStatus.parse_obj(obj)

        _obj = HealthCheckStatus.parse_obj({
            "kafka_delivery_status": obj.get("kafkaDeliveryStatus"),
            "cloud_status": obj.get("cloudStatus")
        })
        return _obj

