# coding: utf-8

# flake8: noqa
"""
    GroupDocs.Translation.ApiGateway.Web

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


# import models into model package
from GroupDocs.Translation.Api.models.auto_post_request import AutoPostRequest
from GroupDocs.Translation.Api.models.cloud_file_response import CloudFileResponse
from GroupDocs.Translation.Api.models.cloud_hugo_response import CloudHugoResponse
from GroupDocs.Translation.Api.models.cloud_text_response import CloudTextResponse
from GroupDocs.Translation.Api.models.csv_file_request import CsvFileRequest
from GroupDocs.Translation.Api.models.health_check_status import HealthCheckStatus
from GroupDocs.Translation.Api.models.http_status_code import HttpStatusCode
from GroupDocs.Translation.Api.models.language_pair_data import LanguagePairData
from GroupDocs.Translation.Api.models.ocr_file_request import OcrFileRequest
from GroupDocs.Translation.Api.models.pdf_file_request import PdfFileRequest
from GroupDocs.Translation.Api.models.presentation_file_request import PresentationFileRequest
from GroupDocs.Translation.Api.models.resx_file_request import ResxFileRequest
from GroupDocs.Translation.Api.models.spreadsheet_file_request import SpreadsheetFileRequest
from GroupDocs.Translation.Api.models.status_response import StatusResponse
from GroupDocs.Translation.Api.models.string_string_tuple import StringStringTuple
from GroupDocs.Translation.Api.models.text_document_file_request import TextDocumentFileRequest
from GroupDocs.Translation.Api.models.text_request import TextRequest
from GroupDocs.Translation.Api.models.url_file_info import UrlFileInfo
from GroupDocs.Translation.Api.models.worksheet_data import WorksheetData
