# coding: utf-8

# flake8: noqa

"""
    GroupDocs.Translation.ApiGateway.Web

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


__version__ = "1.0.0"

# import apis into sdk package
from GroupDocs.Translation.Api.api.transport_api import TransportApi

# import ApiClient
from GroupDocs.Translation.Api.api_response import ApiResponse
from GroupDocs.Translation.Api.api_client import ApiClient
from GroupDocs.Translation.Api.configuration import Configuration
from GroupDocs.Translation.Api.exceptions import OpenApiException
from GroupDocs.Translation.Api.exceptions import ApiTypeError
from GroupDocs.Translation.Api.exceptions import ApiValueError
from GroupDocs.Translation.Api.exceptions import ApiKeyError
from GroupDocs.Translation.Api.exceptions import ApiAttributeError
from GroupDocs.Translation.Api.exceptions import ApiException

# import models into sdk package
from GroupDocs.Translation.Api.models.auto_post_request import AutoPostRequest
from GroupDocs.Translation.Api.models.cloud_file_response import CloudFileResponse
from GroupDocs.Translation.Api.models.cloud_hugo_response import CloudHugoResponse
from GroupDocs.Translation.Api.models.cloud_text_response import CloudTextResponse
from GroupDocs.Translation.Api.models.csv_file_request import CsvFileRequest
from GroupDocs.Translation.Api.models.health_check_status import HealthCheckStatus
from GroupDocs.Translation.Api.models.http_status_code import HttpStatusCode
from GroupDocs.Translation.Api.models.language_pair_data import LanguagePairData
from GroupDocs.Translation.Api.models.ocr_file_request import OcrFileRequest
from GroupDocs.Translation.Api.models.pdf_file_request import PdfFileRequest
from GroupDocs.Translation.Api.models.presentation_file_request import PresentationFileRequest
from GroupDocs.Translation.Api.models.resx_file_request import ResxFileRequest
from GroupDocs.Translation.Api.models.spreadsheet_file_request import SpreadsheetFileRequest
from GroupDocs.Translation.Api.models.status_response import StatusResponse
from GroupDocs.Translation.Api.models.string_string_tuple import StringStringTuple
from GroupDocs.Translation.Api.models.text_document_file_request import TextDocumentFileRequest
from GroupDocs.Translation.Api.models.text_request import TextRequest
from GroupDocs.Translation.Api.models.url_file_info import UrlFileInfo
from GroupDocs.Translation.Api.models.worksheet_data import WorksheetData
